### ISSUE TITLE
Include more publications in the database

### ISSUE THREAD

**Issue by cplee1** [NickSwainston/pulsar_spectra#45]
Our database lacks publications focusing on MSPs, high frequency measurements, and northern-sky pulsars. Here we are keeping a list of publications which may be useful additions to the database.

Flags:
- MSPs: *
- Northern-sky: ^
- Southern-sky: v
- Low-frequencies: L
- High-frequencies: H

List of publications:
- [x] (*^L) [Stappers et al. (2008)](https://ui.adsabs.harvard.edu/abs/2008AIPC..983..593S/abstract)
- [x] (*^L) [Kondratiev et al. (2016)](https://ui.adsabs.harvard.edu/abs/2016A%26A...585A.128K/abstract)
- [x] (^L) [McEwen et al. (2020)](https://ui.adsabs.harvard.edu/abs/2020ApJ...892...76M/abstract)
- [x] (^L) [Kravtsov et al. (2022)](https://ui.adsabs.harvard.edu/abs/2022MNRAS.512.4324K/abstract)
- [x] (vH) [Spiewak et al. (2022)](https://ui.adsabs.harvard.edu/abs/2022arXiv220404115S/abstract)
- [x] (*v) [Toscano et al. (2022)](https://ui.adsabs.harvard.edu/abs/1998ApJ...506..863T/abstract)
- [x] (*^) [Kuzmin & Losovsky (2001)](https://ui.adsabs.harvard.edu/abs/2001A%26A...368..230K/abstract)
- [x] (*^) [Stairs et al. (1999)](https://ui.adsabs.harvard.edu/abs/1999ApJS..123..627S/abstract)

**Comment by NickSwainston** [comment]
We should also include the multibeam papers eg:
https://ui.adsabs.harvard.edu/abs/2001MNRAS.328...17M/abstract

**Comment by NickSwainston** [comment]
> We should also include the multibeam papers eg: https://ui.adsabs.harvard.edu/abs/2001MNRAS.328...17M/abstract

Done

**Comment by NickSwainston** [comment]
[Spiewak et al. (2022)](https://ui.adsabs.harvard.edu/abs/2022arXiv220404115S/abstract) is a combination of previous Meerkat papers' results so we should not include it.

**Comment by NickSwainston** [comment]
I misread the [Spiewak et al. (2022)](https://ui.adsabs.harvard.edu/abs/2022arXiv220404115S/abstract) table, it's not a combination paper so I included it

**Comment by NickSwainston** [comment]
Completed in #56
