### ISSUE TITLE
The link is incorrect.

### ISSUE THREAD

**Issue by harvey0908** [NickSwainston/pulsar_spectra#89]
Dear Swainston, I found that the link of this article is incorrect, please check it.
![微信截图_20240301181448](https://github.com/NickSwainston/pulsar_spectra/assets/87842773/85372796-c96b-4d08-95c9-9ceb23e9ee32)
Here is the new link :https://arxiv.org/abs/1807.00708

**Comment by NickSwainston** [comment]
Fixed in #90
