### ISSUE TITLE
Errors found in Johnston_2018

### ISSUE THREAD

**Issue by QZGao** [NickSwainston/pulsar_spectra#93]
I found an error in the flux data published by Johnston & Kerr (2018). According to their paper, all data labelled "N" are not calibrated and set to zero:

![image](https://github.com/NickSwainston/pulsar_spectra/assets/116619347/46af611f-b471-49f9-8b9e-fc9b672d9f68)

But in the CSV supporting material, there is one line that still has a 0.01 flux density, and has thus entered our pulsar_spectra package database:

![image](https://github.com/NickSwainston/pulsar_spectra/assets/116619347/e034fd15-7382-4131-b2e0-740ab1b8ebe5)

I suggest that this 0.01 is a mistake and best to be removed.

**Comment by QZGao** [comment]
All other pulsars in class N are correctly set to 0 in the CSV file:

![image](https://github.com/NickSwainston/pulsar_spectra/assets/116619347/a66459f0-1cc9-4027-a76b-db172361fa1d)

**Comment by NickSwainston** [comment]
That is a strange error in the CSV file. Thank you for catching it
